# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='function name')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='party name')),
                ('abbrev', models.CharField(max_length=200, verbose_name='abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='RegularStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='speaker name')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.Function')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.Party')),
            ],
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.Speaker', verbose_name='who said it'),
        ),
    ]
