# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of session')),
                ('legislative_period', models.IntegerField(verbose_name='legislative period')),
                ('document_id', models.IntegerField(verbose_name='document per period')),
                ('url', models.CharField(default=None, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='function name')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='party name')),
                ('abbrev', models.CharField(max_length=200, verbose_name='abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='RegularStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('str_adjectives', models.TextField(default=None, verbose_name='standardized adjectives')),
                ('str_nouns', models.TextField(default=None, verbose_name='standardized nouns')),
                ('str_verbs', models.TextField(default=None, verbose_name='standardized verbs')),
                ('str_partizip_i', models.TextField(default=None, null=True, verbose_name='standardized partizip i')),
                ('str_other_words', models.TextField(default=None, verbose_name='other words')),
                ('str_persons', models.TextField(default=None, verbose_name='persons')),
                ('str_titles', models.TextField(default=None, verbose_name='wikipedia titles')),
                ('order_id', models.IntegerField(default=0, verbose_name='order within document')),
                ('page', models.IntegerField(default=0, verbose_name='page where statement begins')),
                ('document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basics.Document', verbose_name='source document')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='speaker name')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.Function')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.Party')),
            ],
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.Speaker', verbose_name='who said it'),
        ),
    ]
