# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_plenarprotokolle', models.IntegerField(default=0, verbose_name='How many Plenarprotokolle in db')),
                ('no_speakers', models.IntegerField(default=0, verbose_name='How many speakers')),
                ('no_functions', models.IntegerField(default=0, verbose_name='How many functions')),
                ('no_parties', models.IntegerField(default=0, verbose_name='How many Parties')),
            ],
        ),
    ]
