# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StmtBlockNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stmt_block_no', models.IntegerField(verbose_name='no of statement_block continuous')),
            ],
        ),
        migrations.AlterField(
            model_name='regularstatement',
            name='stmt_block_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basics.StmtBlockNo', verbose_name='block of statements that where uttered by one speaker directly after another'),
        ),
    ]
