# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20170227_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of session')),
                ('legislative_period', models.IntegerField(verbose_name='legislative period')),
                ('document_id', models.IntegerField(verbose_name='document id')),
            ],
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='order within document'),
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basics.Document', verbose_name='source document'),
        ),
    ]
