# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20170419_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StmtBlockNo',
            new_name='StmtBlock',
        ),
    ]
