# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularstatement',
            name='cleaned_text',
            field=models.TextField(default=None, null=True, verbose_name='only letters'),
        ),
    ]
