# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_auto_20170419_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmtblock',
            name='speaker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.Speaker', verbose_name='who said it'),
        ),
    ]
