# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_auto_20170227_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularstatement',
            name='str_adjectives',
            field=models.TextField(default=None, verbose_name='standardized adjectives'),
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='str_nouns',
            field=models.TextField(default=None, verbose_name='standardized adjectives'),
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='str_other_words',
            field=models.TextField(default=None, verbose_name='other words'),
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='str_partizip_i',
            field=models.TextField(default=None, verbose_name='standardized partizip i'),
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='str_persons',
            field=models.TextField(default=None, verbose_name='persons'),
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='str_titles',
            field=models.TextField(default=None, verbose_name='wikipedia titles'),
        ),
        migrations.AddField(
            model_name='regularstatement',
            name='str_verbs',
            field=models.TextField(default=None, verbose_name='standardized verbs'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.IntegerField(verbose_name='document per period'),
        ),
    ]
