# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_stmtblock_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmtblock',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.Document', verbose_name='who said it'),
        ),
    ]
