# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_auto_20170309_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularstatement',
            name='str_partizip_i',
            field=models.TextField(default=None, null=True, verbose_name='standardized partizip i'),
        ),
    ]
