# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_auto_20170309_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularstatement',
            name='str_nouns',
            field=models.TextField(default=None, verbose_name='standardized nouns'),
        ),
    ]
